### ISSUE TITLE
SysmonSearch not appearing in Kibana

### ISSUE THREAD

**Issue by fawz24** [JPCERTCC/SysmonSearch#3]
I installed ElasticSearch-6.4.2, Kibana-6.4.2 and SysmonSearch on Ubuntu 18.04.
According to the following wiki install steps
>https://github.com/JPCERTCC/SysmonSearch/wiki/how-to-install#kibana-setup

SysmonSearch should be visible on the left menu. Unfortunately it is not.
![screenshot from 2018-10-18 11-20-10](https://user-images.githubusercontent.com/19811530/47175518-fa32a180-d31b-11e8-9508-9c296652e961.png)

How can this be fixed?

**Comment by S03D4-164** [comment]
We are sorry. There was a mistake in step 11 on the wiki.
```bash
(wrong)
$ cp -r sysmon_search_plugin/ $KIBANA_HOME/plugin/

(correct)
$ cp -r sysmon_search_plugin/ $KIBANA_HOME/plugins/
```
Please copy sysmon_search_plugin into **$KIBANA_HOME/plugins** with the "s" at the end, NOT $KIBANA_HOME/plugin.
